ALTER TABLE PERSON ADD name VARCHAR(100);

INSERT INTO PERSON (ID, NAME) VALUES ( NEXTVAL('person_seq'), 'BRYAN');
INSERT INTO PERSON (ID, NAME) VALUES ( NEXTVAL('person_seq'), 'STEVE');
INSERT INTO PERSON (ID, NAME) VALUES ( NEXTVAL('person_seq'), 'FIN');
INSERT INTO PERSON (ID, NAME) VALUES ( NEXTVAL('person_seq'), 'PORTER');
INSERT INTO PERSON (ID, NAME) VALUES ( NEXTVAL('person_seq'), 'JACK');